@AuthorizationPolicy_HostAddress = http://localhost:5196

GET https://localhost:7013/weatherforecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1heGltZXRyZW1ibGF5LXJoZWF1bHQiLCJzdWIiOiJtYXhpbWV0cmVtYmxheS1yaGVhdWx0IiwianRpIjoiMmVjNTRlM2UiLCJzY29wZSI6ImFkbWluIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjcwMTMiLCJodHRwOi8vbG9jYWxob3N0OjUxOTYiXSwibmJmIjoxNzQyMTMzMDA4LCJleHAiOjE3NTAwODE4MDgsImlhdCI6MTc0MjEzMzAwOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.dJSmb_XzLf0Hm1YweDM7HAr7nkQGsl1bs-VUt_Xhkcw
