@AuthorizationPolicy_HostAddress = http://localhost:5196

GET https://localhost:7013/weatherforecast
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1heGltZXRyZW1ibGF5LXJoZWF1bHQiLCJzdWIiOiJtYXhpbWV0cmVtYmxheS1yaGVhdWx0IiwianRpIjoiMmVjNTRlM2UiLCJzY29wZSI6ImFkbWluIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjcwMTMiLCJodHRwOi8vbG9jYWxob3N0OjUxOTYiXSwibmJmIjoxNzQyMTMzMDA4LCJleHAiOjE3NTAwODE4MDgsImlhdCI6MTc0MjEzMzAwOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.dJSmb_XzLf0Hm1YweDM7HAr7nkQGsl1bs-VUt_Xhkcw


###
# user-jwts
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1heGltZXRyZW1ibGF5LXJoZWF1bHQiLCJzdWIiOiJtYXhpbWV0cmVtYmxheS1yaGVhdWx0IiwianRpIjoiZWE1MjI5ZDEiLCJzY29wZSI6ImFkbWluIiwiYXVkIjpbImh0dHBzOi8vbG9jYWxob3N0OjcwMTMiLCJodHRwOi8vbG9jYWxob3N0OjUxOTYiXSwibmJmIjoxNzQxNDQyOTc2LCJleHAiOjE3NDkzOTE3NzYsImlhdCI6MTc0MTQ0Mjk3NiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.0BPfrGQC01LntOx3Cs2P1ZBN6_4-YtI_7Q2V368Y-CQ

# dating-app
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJsaXNhIiwibmJmIjoxNzQxNTMxMDc2LCJleHAiOjE3NDIxMzU4NzYsImlhdCI6MTc0MTUzMTA3Nn0.jwtEKmPKQ5Qs6lYPEy0yjYeuH9cSPISucNuLTwwqqcxWJXCyNjZdNjRpTvS-NQGOFqZ1PEcW0lEQ28Bur2LOqA

"private jwt key private jwt key private jwt key private jwt key private jwt key"